## **Scikit learn - Iris dataset**

In [75]:
from sklearn.datasets import load_iris

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

In [76]:
iris = load_iris()

In [10]:
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [77]:
print(iris.data[0:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [81]:
print(iris.feature_names, '\n')
print(iris.target, '\n')
print(iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 

['setosa' 'versicolor' 'virginica']


In [82]:
print(iris.data.shape[0] == iris.target.shape[0])

True


**Preparing data to pass to scikit learn**

In [83]:
X, y = load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

### **Using KNeighborsClassifier**

In [88]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

y_predicted_knn = knn.predict(X_test)
accuracy_score(y_test, y_predicted_knn)

0.9777777777777777

# for the same data, using LogisticRegression

In [87]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

lgr = LogisticRegression(solver='lbfgs', random_state=1, multi_class='auto')

lgr.fit(X_train, y_train)

y_predicted_lgr = lgr.predict(X_test)

accuracy_score(y_test, y_predicted_lgr)

0.9777777777777777