In [25]:
import numpy as np
import pandas as pd
from pprint import pprint as pp

A = np.arange(8).reshape(2,4) + 0.1
B = np.arange(6).reshape(2,3) + 0.2
C = np.arange(12).reshape(3,4) + 0.3

pp(A)
pp(B)
pp(C)

array([[0.1, 1.1, 2.1, 3.1],
       [4.1, 5.1, 6.1, 7.1]])
array([[0.2, 1.2, 2.2],
       [3.2, 4.2, 5.2]])
array([[ 0.3,  1.3,  2.3,  3.3],
       [ 4.3,  5.3,  6.3,  7.3],
       [ 8.3,  9.3, 10.3, 11.3]])


In [26]:
pp(np.hstack([A,B]))
pp(np.concatenate([A,B],axis=1))

array([[0.1, 1.1, 2.1, 3.1, 0.2, 1.2, 2.2],
       [4.1, 5.1, 6.1, 7.1, 3.2, 4.2, 5.2]])
array([[0.1, 1.1, 2.1, 3.1, 0.2, 1.2, 2.2],
       [4.1, 5.1, 6.1, 7.1, 3.2, 4.2, 5.2]])


In [28]:
pp(np.vstack([A,C]))
pp(np.concatenate([A,C],axis=0))

array([[ 0.1,  1.1,  2.1,  3.1],
       [ 4.1,  5.1,  6.1,  7.1],
       [ 0.3,  1.3,  2.3,  3.3],
       [ 4.3,  5.3,  6.3,  7.3],
       [ 8.3,  9.3, 10.3, 11.3]])
array([[ 0.1,  1.1,  2.1,  3.1],
       [ 4.1,  5.1,  6.1,  7.1],
       [ 0.3,  1.3,  2.3,  3.3],
       [ 4.3,  5.3,  6.3,  7.3],
       [ 8.3,  9.3, 10.3, 11.3]])
