In [4]:
import numpy as np

# give 10 equally spaced numbers bw 0, 5
a = np.linspace(0,5, 10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [7]:
# AXIS

_np = np.array([(1,2),(3,4),(5,6)])
print('Array', _np)
sum_cols = _np.sum(axis=0)
sum_rows = _np.sum(axis=1)
print('sum of rows', sum_rows)
print('sum of columns', sum_cols)

Array [[1 2]
 [3 4]
 [5 6]]
sum of rows [ 3  7 11]
sum of columns [ 9 12]


In [13]:
# STANDARD DEVIATION
std = np.std(_np)
print(std)
print(np.mean(_np))

1.707825127659933
3.5


In [19]:
# VIRTICAL AND HORIZANTAL STACKing
a_1 = np.array([(1,2,3), (4,5,6)])
a_2 = np.array([(7,8,9), (10,11,12)])
v_stacked = np.vstack((a_1, a_2))
h_stacked = np.hstack((a_1, a_2))
print('v_stacked: \n',v_stacked)
print('h_stacked: \n',h_stacked)

v_stacked: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
h_stacked: 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [23]:
# RAVEL
raveled = np.ravel(v_stacked)
print(raveled)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
print(np.sin(a_1))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
