In [13]:
import numpy as np

from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [14]:
min_max_scaler = MinMaxScaler()

In [7]:
mat = np.random.randint(0,100,(10,2))

In [8]:
mat

array([[74, 78],
       [92, 61],
       [77, 24],
       [ 9, 48],
       [61, 13],
       [80, 20],
       [97, 16],
       [73, 73],
       [81, 54],
       [ 8, 57]])

In [12]:
min_max_scaler.fit_transform(mat)

array([[0.74157303, 1.        ],
       [0.94382022, 0.73846154],
       [0.7752809 , 0.16923077],
       [0.01123596, 0.53846154],
       [0.59550562, 0.        ],
       [0.80898876, 0.10769231],
       [1.        , 0.04615385],
       [0.73033708, 0.92307692],
       [0.82022472, 0.63076923],
       [0.        , 0.67692308]])

In [15]:
standard_scaler = StandardScaler()

In [17]:
standard_scaler.fit_transform(mat)

array([[ 0.29458635,  1.46081434],
       [ 0.89714935,  0.72171185],
       [ 0.39501352, -0.88692299],
       [-1.88133558,  0.15651582],
       [-0.14059803, -1.36516578],
       [ 0.49544069, -1.06082946],
       [ 1.06452796, -1.23473593],
       [ 0.26111063,  1.24343125],
       [ 0.52891641,  0.41737552],
       [-1.9148113 ,  0.54780538]])

In [18]:
standard_scaler.fit_transform(mat).min(), standard_scaler.fit_transform(mat).max()

(-1.9148112984013241, 1.460814336985883)